Добавлена новая строка
RoSMag/git-course-pr-example pull request #22
Opened 2023-11-01 11:38 UTC by Deikkue

2023-11-01 11:39 UTC, Hortonq requested changes
Перепиши последнюю строку

2023-11-01 11:39 UTC, Hortonq commented on README.md
> +Два грустных
Гуси должны быть веселыми, детка

2023-11-01 11:43 UTC, Hortonq approved these changes
верю

2023-11-01 11:43 UTC, merged

2023-11-02 09:22 UTC, RoSMag commented
@Deikkue  Строка неверная. 
Ревью от @Hortonq выполнено формально!