Дописана последняя строка
RoSMag/git-course-pr-example pull request #23
Opened 2023-11-01 21:24 UTC by Den4ik110514228

Дописал последнюю строку

2023-11-01 21:24 UTC, Hortonq requested changes
Найдена опечатка

2023-11-01 21:24 UTC, Hortonq commented on README.md
> +Два веселых эЛя
Гуся, а не эЛя...

2023-11-01 21:34 UTC, Hortonq approved these changes
Верю

2023-11-01 21:34 UTC, merged

2023-11-02 09:25 UTC, RoSMag commented
@Den4ik110514228 дописана неправильная строка. повнимательенее.
@Hortonq ревьюир не проверил правильность изменений в пул реквесте.